import Papa from "papaparse";
import { Platform } from "react-native";

export const exportCSV = async (transactions, filename) => {
  const data = transactions.map((t) => ({
    Date: t.date ? new Date(t.date).toLocaleString() : "",
    Type: t.type || "",
    Category: t.category || "",
    Account: t.account || "",
    Amount: t.amount ? t.amount.toFixed(2) : "0.00",
    Note: t.title || "",
  }));

  const csv = Papa.unparse(data);

  if (Platform.OS === "web") {
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return;
  }

    // Mobile: redirect to web for CSV
  const { Linking } = require("react-native");
  const { Alert } = require("react-native");
  Alert.alert(
    "CSV Export",
    "CSV export is available on the web version. Open FinManager web now?",
    [
      { text: "Cancel", style: "cancel" },
      { text: "Open Web", onPress: () => Linking.openURL("https://fin-manager-00000.netlify.app/") },
    ]
  );

  const Print = require("expo-print");
  const Sharing = require("expo-sharing");
  const csvHtml = `<html><body><pre>${csv}</pre></body></html>`;
  const { uri } = await Print.printToFileAsync({ html: csvHtml });
  const csvUri = uri.replace(".pdf", ".csv");
  await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: filename });
};

export const exportPDF = async (reportData, filename) => {
  const { period, totalIncome, totalExpenses, netSavings, savingsRate, categoryData, incomeData, transactions } = reportData;

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,sans-serif;padding:30px;color:#1a1a1a;font-size:12px}
h1{font-size:20px;margin-bottom:2px}
h2{font-size:14px;margin:20px 0 8px;color:#333;border-bottom:1px solid #ddd;padding-bottom:4px}
.period{color:#4F46E5;font-size:13px;margin-bottom:20px}
.summary{display:flex;gap:8px;margin-bottom:20px}
.sc{flex:1;padding:12px;border-radius:8px;text-align:center}
.sc.i{background:#ECFDF5}.sc.e{background:#FEF2F2}.sc.s{background:#EEF2FF}.sc.r{background:#F9FAFB}
.sl{font-size:9px;color:#555;margin-bottom:2px}.sv{font-size:16px;font-weight:bold}
.g{color:#10B981}.rd{color:#EF4444}.b{color:#4F46E5}
table{width:100%;border-collapse:collapse;margin-bottom:16px}
th{background:#F3F4F6;padding:6px 8px;text-align:left;font-size:10px;color:#555;border-bottom:1px solid #ddd}
td{padding:6px 8px;border-bottom:1px solid #f0f0f0;font-size:10px}
.ai{color:#10B981;font-weight:600}.ae{color:#EF4444;font-weight:600}
.footer{margin-top:20px;padding-top:10px;border-top:1px solid #eee;font-size:9px;color:#aaa;text-align:center}
</style></head><body>
<h1>FinManager Report</h1>
<div class="period">${period}</div>
<div class="summary">
<div class="sc i"><div class="sl">Total Income</div><div class="sv g">${totalIncome.toFixed(2)}</div></div>
<div class="sc e"><div class="sl">Total Expenses</div><div class="sv rd">${totalExpenses.toFixed(2)}</div></div>
<div class="sc s"><div class="sl">Net Savings</div><div class="sv ${netSavings >= 0 ? "g" : "rd"}">${netSavings.toFixed(2)}</div></div>
<div class="sc r"><div class="sl">Savings Rate</div><div class="sv b">${savingsRate.toFixed(0)}%</div></div>
</div>
${categoryData.length > 0 ? `<h2>Expense Breakdown</h2><table><thead><tr><th>#</th><th>Category</th><th>Amount</th><th>%</th></tr></thead><tbody>${categoryData.map((c, i) => `<tr><td>${i + 1}</td><td>${c.name}</td><td class="ae">${c.amount.toFixed(2)}</td><td>${totalExpenses > 0 ? ((c.amount / totalExpenses) * 100).toFixed(1) : "0"}%</td></tr>`).join("")}</tbody></table>` : ""}
${incomeData.length > 0 ? `<h2>Income Breakdown</h2><table><thead><tr><th>#</th><th>Category</th><th>Amount</th><th>%</th></tr></thead><tbody>${incomeData.map((c, i) => `<tr><td>${i + 1}</td><td>${c.name}</td><td class="ai">${c.amount.toFixed(2)}</td><td>${totalIncome > 0 ? ((c.amount / totalIncome) * 100).toFixed(1) : "0"}%</td></tr>`).join("")}</tbody></table>` : ""}
<h2>All Transactions</h2><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Account</th><th>Amount</th><th>Note</th></tr></thead><tbody>${transactions.map((t) => `<tr><td>${t.date ? new Date(t.date).toLocaleDateString() : ""}</td><td>${t.type || ""}</td><td>${t.category || ""}</td><td>${t.account || ""}</td><td class="${t.type === "income" ? "ai" : "ae"}">${t.type === "income" ? "+" : "-"}${t.amount ? t.amount.toFixed(2) : "0.00"}</td><td>${t.title && t.title !== "No note" ? t.title : ""}</td></tr>`).join("")}</tbody></table>
<div class="footer">Generated by FinManager - ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</div>
</body></html>`;

  if (Platform.OS === "web") {
    const newWindow = window.open("", "_blank");
    newWindow.document.write(html);
    newWindow.document.close();
    setTimeout(() => newWindow.print(), 500);
    return;
  }

  const Print = require("expo-print");
  const Sharing = require("expo-sharing");
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: `${filename}.pdf` });
};